import type { GameDTO } from "./types";

/**
 * Hand-curated seed catalog used while the BGG API token is pending.
 * Each entry uses the real BGG `objectid`, so once BGG approves the
 * application and `BGG_API_TOKEN` is set the same ids transparently
 * resolve against live BGG without any client-side change.
 *
 * Data points (year, players, playtime, designers) are widely published
 * facts; summaries are paraphrased one-liners written for this app.
 * We deliberately bundle a small, opinionated set of well-known games
 * rather than redistribute a bulk BGG dump.
 *
 * Image URLs point at BGG's public CDN. They are not redistributed by
 * this backend; the iOS client fetches them directly.
 */
export const seedCatalog: readonly GameDTO[] = [
  {
    id: 174430,
    name: "Gloomhaven",
    yearPublished: 2017,
    thumbnailURL:
      "https://cf.geekdo-images.com/sZYp_3BTDGjh2unaZfZmuA__thumb/img/e7GyV4PaNtwmalU-EQAGecwoBSI=/fit-in/200x150/filters:strip_icc()/pic2437871.jpg",
    imageURL:
      "https://cf.geekdo-images.com/sZYp_3BTDGjh2unaZfZmuA__original/img/9zarYfJUfZvT2X-jvBFMRZS8eMI=/0x0/filters:format(jpeg)/pic2437871.jpg",
    summary:
      "Cooperative legacy-style dungeon crawler with branching campaigns and tactical hex combat.",
    minPlayers: 1,
    maxPlayers: 4,
    minPlaytimeMinutes: 60,
    maxPlaytimeMinutes: 120,
    complexity: 3.9,
    categories: ["Adventure", "Fantasy", "Fighting"],
    mechanics: ["Cooperative Game", "Hand Management", "Modular Board"],
    designers: ["Isaac Childres"],
  },
  {
    id: 266192,
    name: "Wingspan",
    yearPublished: 2019,
    thumbnailURL:
      "https://cf.geekdo-images.com/yLZJCVLlIx4c7eJEWUNJ7w__thumb/img/FF7TdgUGgmCkVhPB6tBvhEhz9YA=/fit-in/200x150/filters:strip_icc()/pic4458123.jpg",
    imageURL:
      "https://cf.geekdo-images.com/yLZJCVLlIx4c7eJEWUNJ7w__original/img/dNc980yawRARD25T-touD51Tc-A=/0x0/filters:format(jpeg)/pic4458123.jpg",
    summary:
      "Engine-builder where you attract a stunning collection of birds to your nature reserves.",
    minPlayers: 1,
    maxPlayers: 5,
    minPlaytimeMinutes: 40,
    maxPlaytimeMinutes: 70,
    complexity: 2.4,
    categories: ["Animals", "Educational"],
    mechanics: ["Engine Building", "Card Drafting", "Set Collection"],
    designers: ["Elizabeth Hargrave"],
  },
  {
    id: 230802,
    name: "Azul",
    yearPublished: 2017,
    thumbnailURL:
      "https://cf.geekdo-images.com/aPSHJO0d0XOpQR5X-wJonw__thumb/img/8nKJYY5ouFcfX7sFqSFBN-uorWQ=/fit-in/200x150/filters:strip_icc()/pic6973671.png",
    imageURL:
      "https://cf.geekdo-images.com/aPSHJO0d0XOpQR5X-wJonw__original/img/QbcS8aB8M0ChGuGl6gGjyl5jcps=/0x0/filters:format(png)/pic6973671.png",
    summary: "Drafting beautiful tiles to decorate the walls of the Royal Palace of Evora.",
    minPlayers: 2,
    maxPlayers: 4,
    minPlaytimeMinutes: 30,
    maxPlaytimeMinutes: 45,
    complexity: 1.8,
    categories: ["Abstract Strategy"],
    mechanics: ["Pattern Building", "Drafting", "Set Collection"],
    designers: ["Michael Kiesling"],
  },
  {
    id: 162886,
    name: "Spirit Island",
    yearPublished: 2017,
    thumbnailURL:
      "https://cf.geekdo-images.com/kjBSKijz5kK17UXKa3pxgg__thumb/img/cQnfDOGnnxZJaTmsgbGDKZjpZTs=/fit-in/200x150/filters:strip_icc()/pic3615739.png",
    imageURL:
      "https://cf.geekdo-images.com/kjBSKijz5kK17UXKa3pxgg__original/img/JUobicKp4hCoenku2nIysiGJTpo=/0x0/filters:format(png)/pic3615739.png",
    summary: "Cooperative settler-destruction where players are spirits defending their island.",
    minPlayers: 1,
    maxPlayers: 4,
    minPlaytimeMinutes: 90,
    maxPlaytimeMinutes: 120,
    complexity: 4.0,
    categories: ["Fantasy", "Mythology"],
    mechanics: ["Cooperative Game", "Variable Powers", "Action Programming"],
    designers: ["R. Eric Reuss"],
  },
  {
    id: 199792,
    name: "Everdell",
    yearPublished: 2018,
    thumbnailURL:
      "https://cf.geekdo-images.com/h2IKiB-ru9_e8xKp4SqRcw__thumb/img/MFr66tA6KGE4d_NUnMcyWiwSGfM=/fit-in/200x150/filters:strip_icc()/pic3918905.jpg",
    imageURL:
      "https://cf.geekdo-images.com/h2IKiB-ru9_e8xKp4SqRcw__original/img/oxR4otgKPaIB-XQ9Im5omNcOUJg=/0x0/filters:format(jpeg)/pic3918905.jpg",
    summary: "Build a city of critters and constructions over four seasons in a charming forest.",
    minPlayers: 1,
    maxPlayers: 4,
    minPlaytimeMinutes: 40,
    maxPlaytimeMinutes: 80,
    complexity: 2.8,
    categories: ["Animals", "City Building"],
    mechanics: ["Worker Placement", "Card Drafting", "Tableau Building"],
    designers: ["James A. Wilson"],
  },
  {
    id: 13,
    name: "Catan",
    yearPublished: 1995,
    thumbnailURL:
      "https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ7H8yw__thumb/img/0E7Yzr9XwbTmfeg_kjIPP6JbIRk=/fit-in/200x150/filters:strip_icc()/pic2419375.jpg",
    imageURL:
      "https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ7H8yw__original/img/2Lxv1jhmt-Y0e3xq9rTPRxXldVg=/0x0/filters:format(jpeg)/pic2419375.jpg",
    summary: "Trade, build, and settle the island of Catan in this modern classic.",
    minPlayers: 3,
    maxPlayers: 4,
    minPlaytimeMinutes: 60,
    maxPlaytimeMinutes: 120,
    complexity: 2.3,
    categories: ["Negotiation", "Economic"],
    mechanics: ["Dice Rolling", "Trading", "Network and Route Building"],
    designers: ["Klaus Teuber"],
  },
  {
    id: 68448,
    name: "7 Wonders",
    yearPublished: 2010,
    thumbnailURL:
      "https://cf.geekdo-images.com/35h9Za_JvMMMtx_92kT0Hg__thumb/img/3spcKm9Eih_PFm8r99HpAUJzfa8=/fit-in/200x150/filters:strip_icc()/pic860217.jpg",
    imageURL:
      "https://cf.geekdo-images.com/35h9Za_JvMMMtx_92kT0Hg__original/img/Q8WjDRWYPwSNrJSTZjsM8B5BO_g=/0x0/filters:format(jpeg)/pic860217.jpg",
    summary: "Lead one of the seven great cities of the ancient world through three ages.",
    minPlayers: 3,
    maxPlayers: 7,
    minPlaytimeMinutes: 30,
    maxPlaytimeMinutes: 30,
    complexity: 2.3,
    categories: ["Ancient", "Card Game"],
    mechanics: ["Card Drafting", "Set Collection", "Simultaneous Action Selection"],
    designers: ["Antoine Bauza"],
  },
  {
    id: 9209,
    name: "Ticket to Ride",
    yearPublished: 2004,
    thumbnailURL:
      "https://cf.geekdo-images.com/ZWJg0dCdrWHxVnc0eFXK8w__thumb/img/iUbJK5Nhg-DgKmnwI-_W8tFGm6w=/fit-in/200x150/filters:strip_icc()/pic38668.jpg",
    imageURL:
      "https://cf.geekdo-images.com/ZWJg0dCdrWHxVnc0eFXK8w__original/img/6c41sTPqMhfYoYM-5JQhi9_NorM=/0x0/filters:format(jpeg)/pic38668.jpg",
    summary: "Collect train cards and claim railway routes across North America.",
    minPlayers: 2,
    maxPlayers: 5,
    minPlaytimeMinutes: 30,
    maxPlaytimeMinutes: 60,
    complexity: 1.9,
    categories: ["Trains", "Family Game"],
    mechanics: ["Set Collection", "Network and Route Building", "Hand Management"],
    designers: ["Alan R. Moon"],
  },
  {
    id: 167791,
    name: "Terraforming Mars",
    yearPublished: 2016,
    thumbnailURL:
      "https://cf.geekdo-images.com/wg9oOLcsKvDesSUdZQ4rxw__thumb/img/BTxqxgYay5tHJfVoJ2NF5g43_gA=/fit-in/200x150/filters:strip_icc()/pic3536616.jpg",
    imageURL:
      "https://cf.geekdo-images.com/wg9oOLcsKvDesSUdZQ4rxw__original/img/thIqWDnH9utKuoKVEUqveDixprI=/0x0/filters:format(jpeg)/pic3536616.jpg",
    summary: "Compete as corporations to terraform Mars, raising oceans, oxygen, and temperature.",
    minPlayers: 1,
    maxPlayers: 5,
    minPlaytimeMinutes: 120,
    maxPlaytimeMinutes: 120,
    complexity: 3.2,
    categories: ["Economic", "Environmental", "Science Fiction"],
    mechanics: ["Card Drafting", "Hand Management", "Tile Placement"],
    designers: ["Jacob Fryxelius"],
  },
  {
    id: 224517,
    name: "Brass: Birmingham",
    yearPublished: 2018,
    thumbnailURL:
      "https://cf.geekdo-images.com/x3zxjr-Vw5iU4yDPg70Jgw__thumb/img/u8DBLG6BPcpdRP_LIs7-_3l9pyc=/fit-in/200x150/filters:strip_icc()/pic3490053.jpg",
    imageURL:
      "https://cf.geekdo-images.com/x3zxjr-Vw5iU4yDPg70Jgw__original/img/FpyxlSVOLEsdXcTOPGXpgBaJYjU=/0x0/filters:format(jpeg)/pic3490053.jpg",
    summary: "Industrial-revolution economic strategy across Birmingham's canal and rail networks.",
    minPlayers: 2,
    maxPlayers: 4,
    minPlaytimeMinutes: 60,
    maxPlaytimeMinutes: 120,
    complexity: 3.9,
    categories: ["Economic", "Industry / Manufacturing"],
    mechanics: ["Hand Management", "Network and Route Building", "Loans"],
    designers: ["Martin Wallace"],
  },
  {
    id: 233078,
    name: "Twilight Imperium: Fourth Edition",
    yearPublished: 2017,
    thumbnailURL:
      "https://cf.geekdo-images.com/_Ppn5lssO5OaildSE9ttmA__thumb/img/H5Mq4-tZsLFQYrLPRk_KmADRdEY=/fit-in/200x150/filters:strip_icc()/pic3727516.jpg",
    imageURL:
      "https://cf.geekdo-images.com/_Ppn5lssO5OaildSE9ttmA__original/img/dCsQrTPtzKDMxoBrekrInqMNbsE=/0x0/filters:format(jpeg)/pic3727516.jpg",
    summary: "Epic 4X space opera: alien factions vie for dominion of the galaxy in a single colossal session.",
    minPlayers: 3,
    maxPlayers: 6,
    minPlaytimeMinutes: 240,
    maxPlaytimeMinutes: 480,
    complexity: 4.3,
    categories: ["Civilization", "Negotiation", "Science Fiction"],
    mechanics: ["Variable Powers", "Area Control", "Trading"],
    designers: ["Christian T. Petersen", "Dane Beltrami"],
  },
  {
    id: 187645,
    name: "Star Wars: Rebellion",
    yearPublished: 2016,
    thumbnailURL:
      "https://cf.geekdo-images.com/L8Q-Z89J7uba9DqOrsQbkg__thumb/img/qchU6h5pMQQVcHZmCwMa3PYRGwY=/fit-in/200x150/filters:strip_icc()/pic2737530.jpg",
    imageURL:
      "https://cf.geekdo-images.com/L8Q-Z89J7uba9DqOrsQbkg__original/img/oseG-pGugZWh8FFLuqaqVnyShao=/0x0/filters:format(jpeg)/pic2737530.jpg",
    summary: "Asymmetric Galactic Civil War: hidden Rebel base versus Imperial sweep across the galaxy.",
    minPlayers: 2,
    maxPlayers: 4,
    minPlaytimeMinutes: 180,
    maxPlaytimeMinutes: 240,
    complexity: 3.7,
    categories: ["Movies / TV / Radio theme", "Science Fiction", "Wargame"],
    mechanics: ["Area Control", "Dice Rolling", "Variable Powers"],
    designers: ["Corey Konieczka"],
  },
  {
    id: 161936,
    name: "Pandemic Legacy: Season 1",
    yearPublished: 2015,
    thumbnailURL:
      "https://cf.geekdo-images.com/-Qer2BBPG7qGGDu6KcVDIw__thumb/img/qIhDX-ce1JsbCGpUC8YYn4VFmLY=/fit-in/200x150/filters:strip_icc()/pic2452831.png",
    imageURL:
      "https://cf.geekdo-images.com/-Qer2BBPG7qGGDu6KcVDIw__original/img/MA0xrhDtzgCdAumpLiFRXSSDdrA=/0x0/filters:format(png)/pic2452831.png",
    summary: "Cooperative twelve-month legacy campaign saving the world from cascading outbreaks.",
    minPlayers: 2,
    maxPlayers: 4,
    minPlaytimeMinutes: 60,
    maxPlaytimeMinutes: 60,
    complexity: 2.8,
    categories: ["Environmental", "Medical"],
    mechanics: ["Cooperative Game", "Legacy", "Variable Powers"],
    designers: ["Rob Daviau", "Matt Leacock"],
  },
  {
    id: 220308,
    name: "Gaia Project",
    yearPublished: 2017,
    thumbnailURL:
      "https://cf.geekdo-images.com/ham5SgRTu4-IVWBXMYZxzg__thumb/img/0AhWsGm_R28UB5xVuxGXKM5gERY=/fit-in/200x150/filters:strip_icc()/pic5375625.png",
    imageURL:
      "https://cf.geekdo-images.com/ham5SgRTu4-IVWBXMYZxzg__original/img/y0YWRMrMQADwyeMlLg3xT2_M28U=/0x0/filters:format(png)/pic5375625.png",
    summary: "Heavy economic 4X engine: alien factions terraform planets across a hexagonal galaxy.",
    minPlayers: 1,
    maxPlayers: 4,
    minPlaytimeMinutes: 60,
    maxPlaytimeMinutes: 150,
    complexity: 4.4,
    categories: ["Economic", "Science Fiction", "Territory Building"],
    mechanics: ["Area Control", "Network and Route Building", "Variable Powers"],
    designers: ["Jens Drögemüller", "Helge Ostertag"],
  },
  {
    id: 36218,
    name: "Dominion",
    yearPublished: 2008,
    thumbnailURL:
      "https://cf.geekdo-images.com/JUAUWaVmppI23k1tCwQc7w__thumb/img/0WJYqqCq11Q5pdtP0AItRXX73R8=/fit-in/200x150/filters:strip_icc()/pic394356.jpg",
    imageURL:
      "https://cf.geekdo-images.com/JUAUWaVmppI23k1tCwQc7w__original/img/Wm-vWBMplXxWaVSAqK9aPxTV4Bk=/0x0/filters:format(jpeg)/pic394356.jpg",
    summary: "The deck-builder that started a genre: buy cards, shuffle them in, build a kingdom.",
    minPlayers: 2,
    maxPlayers: 4,
    minPlaytimeMinutes: 30,
    maxPlaytimeMinutes: 30,
    complexity: 2.4,
    categories: ["Card Game", "Medieval"],
    mechanics: ["Deck Building", "Hand Management"],
    designers: ["Donald X. Vaccarino"],
  },
  {
    id: 12333,
    name: "Twilight Struggle",
    yearPublished: 2005,
    thumbnailURL:
      "https://cf.geekdo-images.com/pNCiUUphnoeWOYfsWq0kng__thumb/img/MwdkBaA92lFZF2_BQXgIrh-cVLU=/fit-in/200x150/filters:strip_icc()/pic361592.jpg",
    imageURL:
      "https://cf.geekdo-images.com/pNCiUUphnoeWOYfsWq0kng__original/img/ehwdXSXpgKNS_n8wBoiP-X8wfck=/0x0/filters:format(jpeg)/pic361592.jpg",
    summary: "Two-player Cold War card-driven brinkmanship from Truman to Gorbachev.",
    minPlayers: 2,
    maxPlayers: 2,
    minPlaytimeMinutes: 120,
    maxPlaytimeMinutes: 180,
    complexity: 3.6,
    categories: ["Modern Warfare", "Political", "Wargame"],
    mechanics: ["Area Control", "Card Driven", "Dice Rolling"],
    designers: ["Ananda Gupta", "Jason Matthews"],
  },
  {
    id: 169786,
    name: "Scythe",
    yearPublished: 2016,
    thumbnailURL:
      "https://cf.geekdo-images.com/7k_nOxpO9OGIjhLq2BUZdA__thumb/img/eqMUVDjA_TxqBBGAbBZ9CjbqUuo=/fit-in/200x150/filters:strip_icc()/pic3163924.jpg",
    imageURL:
      "https://cf.geekdo-images.com/7k_nOxpO9OGIjhLq2BUZdA__original/img/7Js_GeOKHIO0wRVTzlz5lZX9rW8=/0x0/filters:format(jpeg)/pic3163924.jpg",
    summary: "Alternate-1920s Eastern Europe: factions race for resources and territory with mechs.",
    minPlayers: 1,
    maxPlayers: 5,
    minPlaytimeMinutes: 90,
    maxPlaytimeMinutes: 115,
    complexity: 3.4,
    categories: ["Economic", "Fighting", "Science Fiction"],
    mechanics: ["Area Control", "Variable Powers", "Worker Placement"],
    designers: ["Jamey Stegmaier"],
  },
  {
    id: 295770,
    name: "Frosthaven",
    yearPublished: 2022,
    thumbnailURL:
      "https://cf.geekdo-images.com/TvclR7ow_kxWhA6T6L2RYg__thumb/img/eyDQkQQuZcg2Y8ENal1HM2yArh0=/fit-in/200x150/filters:strip_icc()/pic6536142.png",
    imageURL:
      "https://cf.geekdo-images.com/TvclR7ow_kxWhA6T6L2RYg__original/img/zNYHxr-CCmxQz0aAd2tqaY1KVok=/0x0/filters:format(png)/pic6536142.png",
    summary: "Successor to Gloomhaven: 100+ scenario campaign, new classes, base-building.",
    minPlayers: 1,
    maxPlayers: 4,
    minPlaytimeMinutes: 60,
    maxPlaytimeMinutes: 180,
    complexity: 3.9,
    categories: ["Adventure", "Exploration", "Fantasy"],
    mechanics: ["Cooperative Game", "Hand Management", "Legacy"],
    designers: ["Isaac Childres"],
  },
  {
    id: 244521,
    name: "The Crew: The Quest for Planet Nine",
    yearPublished: 2019,
    thumbnailURL:
      "https://cf.geekdo-images.com/9wfvYR-c_kU6jq1rxojqUg__thumb/img/eMAqHO11Lg6sCEQF6YMzUJEznTM=/fit-in/200x150/filters:strip_icc()/pic4885814.jpg",
    imageURL:
      "https://cf.geekdo-images.com/9wfvYR-c_kU6jq1rxojqUg__original/img/Ojzep_y2lI5ABT_7vsMcwH7iQjQ=/0x0/filters:format(jpeg)/pic4885814.jpg",
    summary: "Cooperative trick-taking: 50 escalating space missions, almost no table talk allowed.",
    minPlayers: 3,
    maxPlayers: 5,
    minPlaytimeMinutes: 20,
    maxPlaytimeMinutes: 20,
    complexity: 1.9,
    categories: ["Card Game", "Science Fiction"],
    mechanics: ["Cooperative Game", "Trick-taking", "Communication Limits"],
    designers: ["Thomas Sing"],
  },
  {
    id: 102794,
    name: "Caverna: The Cave Farmers",
    yearPublished: 2013,
    thumbnailURL:
      "https://cf.geekdo-images.com/BvIfDkddre6saUoYJZHbxg__thumb/img/uJtcZRsq3KQNu3o6SEVCjJzJjo8=/fit-in/200x150/filters:strip_icc()/pic1632539.jpg",
    imageURL:
      "https://cf.geekdo-images.com/BvIfDkddre6saUoYJZHbxg__original/img/jx-O7zKnfRIzM93pGPOyVOzZcvg=/0x0/filters:format(jpeg)/pic1632539.jpg",
    summary: "Dwarves dig caves, raise animals, and arm warriors in this beefy worker-placement.",
    minPlayers: 1,
    maxPlayers: 7,
    minPlaytimeMinutes: 30,
    maxPlaytimeMinutes: 210,
    complexity: 3.8,
    categories: ["Animals", "Economic", "Farming"],
    mechanics: ["Worker Placement", "Tile Placement", "Variable Powers"],
    designers: ["Uwe Rosenberg"],
  },
  {
    id: 124361,
    name: "Concordia",
    yearPublished: 2013,
    thumbnailURL:
      "https://cf.geekdo-images.com/RIxnNb7HCQukboe6Qxv8jQ__thumb/img/Yj6XAelcLOlDP9-LrONIKMljxsg=/fit-in/200x150/filters:strip_icc()/pic2814784.jpg",
    imageURL:
      "https://cf.geekdo-images.com/RIxnNb7HCQukboe6Qxv8jQ__original/img/HGtSXoIYQGfIDmPzsmPL_tUlVRk=/0x0/filters:format(jpeg)/pic2814784.jpg",
    summary: "Roman trade & expansion: tight, elegant, no luck. Score by combinations of bought cards.",
    minPlayers: 2,
    maxPlayers: 5,
    minPlaytimeMinutes: 60,
    maxPlaytimeMinutes: 120,
    complexity: 3.0,
    categories: ["Ancient", "Economic"],
    mechanics: ["Hand Management", "Network and Route Building", "Set Collection"],
    designers: ["Mac Gerdts"],
  },
  {
    id: 120677,
    name: "Terra Mystica",
    yearPublished: 2012,
    thumbnailURL:
      "https://cf.geekdo-images.com/Co9kOWnvO_5wLNYjyABe-w__thumb/img/JiH_kPpEi_kn5pfa3KPPtP6OIVk=/fit-in/200x150/filters:strip_icc()/pic1356616.jpg",
    imageURL:
      "https://cf.geekdo-images.com/Co9kOWnvO_5wLNYjyABe-w__original/img/_atIZpZWE2-MhbYJ6yyAtKsmxBE=/0x0/filters:format(jpeg)/pic1356616.jpg",
    summary: "Fourteen fantasy factions reshape the land to suit them in this heavy euro.",
    minPlayers: 2,
    maxPlayers: 5,
    minPlaytimeMinutes: 60,
    maxPlaytimeMinutes: 150,
    complexity: 3.9,
    categories: ["Civilization", "Economic", "Fantasy"],
    mechanics: ["Area Control", "Variable Powers", "Network and Route Building"],
    designers: ["Helge Ostertag", "Jens Drögemüller"],
  },
  {
    id: 96848,
    name: "Mage Knight Board Game",
    yearPublished: 2011,
    thumbnailURL:
      "https://cf.geekdo-images.com/EZIPDFeOay-A5IvJDGTbDQ__thumb/img/6IGTbnOkv0wXsIw3aMOMl8RVNqs=/fit-in/200x150/filters:strip_icc()/pic1083380.jpg",
    imageURL:
      "https://cf.geekdo-images.com/EZIPDFeOay-A5IvJDGTbDQ__original/img/M5R6yOmuk9PRvVWKnBNCQOcO9Vo=/0x0/filters:format(jpeg)/pic1083380.jpg",
    summary: "Solo-friendly fantasy adventure: deck-building meets exploration meets puzzle combat.",
    minPlayers: 1,
    maxPlayers: 4,
    minPlaytimeMinutes: 60,
    maxPlaytimeMinutes: 240,
    complexity: 4.3,
    categories: ["Adventure", "Exploration", "Fantasy"],
    mechanics: ["Deck Building", "Hand Management", "Variable Powers"],
    designers: ["Vlaada Chvátil"],
  },
  {
    id: 14996,
    name: "Ticket to Ride: Europe",
    yearPublished: 2005,
    thumbnailURL:
      "https://cf.geekdo-images.com/Pivpt0G5d7v_qP9NQVGuog__thumb/img/jHWDAFD0iLfvY1hvciYXyxLLZ-A=/fit-in/200x150/filters:strip_icc()/pic66668.jpg",
    imageURL:
      "https://cf.geekdo-images.com/Pivpt0G5d7v_qP9NQVGuog__original/img/QnxLEgEiv26WYxL6f2YVT80sm00=/0x0/filters:format(jpeg)/pic66668.jpg",
    summary: "Connect European cities by train; tunnels, ferries, and stations spice the original.",
    minPlayers: 2,
    maxPlayers: 5,
    minPlaytimeMinutes: 30,
    maxPlaytimeMinutes: 60,
    complexity: 1.9,
    categories: ["Trains", "Family Game"],
    mechanics: ["Set Collection", "Network and Route Building", "Hand Management"],
    designers: ["Alan R. Moon"],
  },
  {
    id: 30549,
    name: "Pandemic",
    yearPublished: 2008,
    thumbnailURL:
      "https://cf.geekdo-images.com/S3ybV1LAp-8SnHIXLLjVqA__thumb/img/oqViRj6nVxK3m36NN1ngGaeAtIs=/fit-in/200x150/filters:strip_icc()/pic1534148.jpg",
    imageURL:
      "https://cf.geekdo-images.com/S3ybV1LAp-8SnHIXLLjVqA__original/img/oNZRdHiFPPkuJq2ne2Q-WMUFmKE=/0x0/filters:format(jpeg)/pic1534148.jpg",
    summary: "Cooperate to cure four diseases racing across the globe before they go pandemic.",
    minPlayers: 2,
    maxPlayers: 4,
    minPlaytimeMinutes: 45,
    maxPlaytimeMinutes: 45,
    complexity: 2.4,
    categories: ["Environmental", "Medical"],
    mechanics: ["Cooperative Game", "Hand Management", "Variable Powers"],
    designers: ["Matt Leacock"],
  },
  {
    id: 31260,
    name: "Agricola",
    yearPublished: 2007,
    thumbnailURL:
      "https://cf.geekdo-images.com/cP856HOqWAgCl_ESL3IchA__thumb/img/CkNKlxKbvVmbIBfwK4bQzfgN3lo=/fit-in/200x150/filters:strip_icc()/pic831744.jpg",
    imageURL:
      "https://cf.geekdo-images.com/cP856HOqWAgCl_ESL3IchA__original/img/IS6XfWPx5d5K7ZDPlOqxVwQDvto=/0x0/filters:format(jpeg)/pic831744.jpg",
    summary: "17th-century farming: feed your family while expanding fields, pastures, and pens.",
    minPlayers: 1,
    maxPlayers: 5,
    minPlaytimeMinutes: 30,
    maxPlaytimeMinutes: 150,
    complexity: 3.6,
    categories: ["Economic", "Farming"],
    mechanics: ["Worker Placement", "Hand Management", "Variable Powers"],
    designers: ["Uwe Rosenberg"],
  },
  {
    id: 28720,
    name: "Brass: Lancashire",
    yearPublished: 2007,
    thumbnailURL:
      "https://cf.geekdo-images.com/jZNVsh2IgexXOAvUeXKi8w__thumb/img/0w8VC36Vb1dh5AwcUfQA3rZsk-w=/fit-in/200x150/filters:strip_icc()/pic3469216.jpg",
    imageURL:
      "https://cf.geekdo-images.com/jZNVsh2IgexXOAvUeXKi8w__original/img/X-l7jU8q11qzSmCGMA0K2_LxYpA=/0x0/filters:format(jpeg)/pic3469216.jpg",
    summary: "The original Brass: Industrial Revolution Lancashire, cotton mills and canals.",
    minPlayers: 2,
    maxPlayers: 4,
    minPlaytimeMinutes: 60,
    maxPlaytimeMinutes: 120,
    complexity: 3.8,
    categories: ["Economic", "Industry / Manufacturing"],
    mechanics: ["Hand Management", "Network and Route Building"],
    designers: ["Martin Wallace"],
  },
  {
    id: 70323,
    name: "King of Tokyo",
    yearPublished: 2011,
    thumbnailURL:
      "https://cf.geekdo-images.com/lQ0J6XsFy3D4S6grDnQc1g__thumb/img/d9zTwLDLLXY4YH5N6dW8pTdC2bY=/fit-in/200x150/filters:strip_icc()/pic3043734.jpg",
    imageURL:
      "https://cf.geekdo-images.com/lQ0J6XsFy3D4S6grDnQc1g__original/img/9Y6YHj82_6mZLE5rtEJBnLo3Cz0=/0x0/filters:format(jpeg)/pic3043734.jpg",
    summary: "Mutant monsters smash Tokyo. Yahtzee-with-teeth dice chucker, plays in 30 minutes.",
    minPlayers: 2,
    maxPlayers: 6,
    minPlaytimeMinutes: 30,
    maxPlaytimeMinutes: 30,
    complexity: 1.5,
    categories: ["Dice", "Fighting", "Science Fiction"],
    mechanics: ["Dice Rolling", "Player Elimination", "Variable Powers"],
    designers: ["Richard Garfield"],
  },
  {
    id: 25613,
    name: "Through the Ages: A New Story of Civilization",
    yearPublished: 2015,
    thumbnailURL:
      "https://cf.geekdo-images.com/3w_5z3MQ2JKb-IhjIovEOg__thumb/img/SJDtnlx1cAbz8RCoDCO8tzeZkRA=/fit-in/200x150/filters:strip_icc()/pic2663291.png",
    imageURL:
      "https://cf.geekdo-images.com/3w_5z3MQ2JKb-IhjIovEOg__original/img/V4mwNu5UOk6tbOjIN5jCKJxntz0=/0x0/filters:format(png)/pic2663291.png",
    summary: "Civ-builder card game: economy, military, science, and culture from antiquity to the modern age.",
    minPlayers: 2,
    maxPlayers: 4,
    minPlaytimeMinutes: 120,
    maxPlaytimeMinutes: 240,
    complexity: 4.4,
    categories: ["Card Game", "Civilization", "Economic"],
    mechanics: ["Card Drafting", "Hand Management", "Tech Trees"],
    designers: ["Vlaada Chvátil"],
  },
  {
    id: 173346,
    name: "7 Wonders Duel",
    yearPublished: 2015,
    thumbnailURL:
      "https://cf.geekdo-images.com/UZcWPS_eyMlg9DvUtFKYsg__thumb/img/yxPOQVfDR2BgqeAGiqA_QfGy7gQ=/fit-in/200x150/filters:strip_icc()/pic2631145.jpg",
    imageURL:
      "https://cf.geekdo-images.com/UZcWPS_eyMlg9DvUtFKYsg__original/img/7yY6OSoeZcYQ2qNlNMzJMBgRzMo=/0x0/filters:format(jpeg)/pic2631145.jpg",
    summary: "Tight head-to-head civilization tableau builder; three age cards laid out in patterns.",
    minPlayers: 2,
    maxPlayers: 2,
    minPlaytimeMinutes: 30,
    maxPlaytimeMinutes: 30,
    complexity: 2.2,
    categories: ["Ancient", "Card Game"],
    mechanics: ["Card Drafting", "Hand Management", "Set Collection"],
    designers: ["Antoine Bauza", "Bruno Cathala"],
  },
  {
    id: 209010,
    name: "Mechs vs. Minions",
    yearPublished: 2016,
    thumbnailURL:
      "https://cf.geekdo-images.com/nIPJDLE9ywtjvAUKuJSPEQ__thumb/img/AfOCBP1VjMS1wq37Trq2GD-VxR0=/fit-in/200x150/filters:strip_icc()/pic3201410.png",
    imageURL:
      "https://cf.geekdo-images.com/nIPJDLE9ywtjvAUKuJSPEQ__original/img/8nm49Pf3xMhRu5kKYNs9zhzifaY=/0x0/filters:format(png)/pic3201410.png",
    summary: "Cooperative mech-piloting programmable-action campaign set in the League of Legends universe.",
    minPlayers: 2,
    maxPlayers: 4,
    minPlaytimeMinutes: 60,
    maxPlaytimeMinutes: 90,
    complexity: 2.6,
    categories: ["Adventure", "Fantasy", "Fighting"],
    mechanics: ["Action Programming", "Cooperative Game", "Modular Board"],
    designers: ["Riot Games"],
  },
  {
    id: 822,
    name: "Carcassonne",
    yearPublished: 2000,
    thumbnailURL:
      "https://cf.geekdo-images.com/okM0dq_bEXnbyEXpYBNdNw__thumb/img/8sIyIuRKHRNUDPdF14kjwXEZHaA=/fit-in/200x150/filters:strip_icc()/pic6544250.png",
    imageURL:
      "https://cf.geekdo-images.com/okM0dq_bEXnbyEXpYBNdNw__original/img/A9pAQQTPSeAZ7wm1HZL8Q8mKbcE=/0x0/filters:format(png)/pic6544250.png",
    summary: "Place tiles, claim cities, roads, and farms with your meeples in medieval France.",
    minPlayers: 2,
    maxPlayers: 5,
    minPlaytimeMinutes: 30,
    maxPlaytimeMinutes: 45,
    complexity: 1.9,
    categories: ["Medieval", "Territory Building"],
    mechanics: ["Tile Placement", "Area Control", "Set Collection"],
    designers: ["Klaus-Jürgen Wrede"],
  },
  {
    id: 178900,
    name: "Codenames",
    yearPublished: 2015,
    thumbnailURL:
      "https://cf.geekdo-images.com/F_KDEu0GjdClml8N7c8Imw__thumb/img/p_uMG2eJYsFZTBysjJZRTPmpenc=/fit-in/200x150/filters:strip_icc()/pic2582929.jpg",
    imageURL:
      "https://cf.geekdo-images.com/F_KDEu0GjdClml8N7c8Imw__original/img/W26nkDvY2c1HoQE3Kv0RIaTBoiU=/0x0/filters:format(jpeg)/pic2582929.jpg",
    summary: "Two spymasters give one-word clues to make their team guess words on the table.",
    minPlayers: 2,
    maxPlayers: 8,
    minPlaytimeMinutes: 15,
    maxPlaytimeMinutes: 15,
    complexity: 1.3,
    categories: ["Card Game", "Deduction", "Party Game"],
    mechanics: ["Communication Limits", "Memory", "Press Your Luck"],
    designers: ["Vlaada Chvátil"],
  },
  {
    id: 822999,
    name: "Splendor",
    yearPublished: 2014,
    thumbnailURL:
      "https://cf.geekdo-images.com/rwOMxx4q5yuElIvo-1-OFw__thumb/img/yqmEPS_E_E50nhwWrEsFh4MFRK4=/fit-in/200x150/filters:strip_icc()/pic1904079.jpg",
    imageURL:
      "https://cf.geekdo-images.com/rwOMxx4q5yuElIvo-1-OFw__original/img/_iJchgkqzrjGkkWmidstzSzpEN8=/0x0/filters:format(jpeg)/pic1904079.jpg",
    summary: "Renaissance gem-buying engine: chips become cards, cards become discounts, points stack.",
    minPlayers: 2,
    maxPlayers: 4,
    minPlaytimeMinutes: 30,
    maxPlaytimeMinutes: 30,
    complexity: 1.8,
    categories: ["Card Game", "Economic", "Renaissance"],
    mechanics: ["Set Collection"],
    designers: ["Marc André"],
  },
  {
    id: 28143,
    name: "Race for the Galaxy",
    yearPublished: 2007,
    thumbnailURL:
      "https://cf.geekdo-images.com/UAfgWl6GIRlnYdDtdh9ZWA__thumb/img/9F3Ne7KBpgBNOcSnOOmVmubsoYU=/fit-in/200x150/filters:strip_icc()/pic361661.jpg",
    imageURL:
      "https://cf.geekdo-images.com/UAfgWl6GIRlnYdDtdh9ZWA__original/img/8mwFy4kP5nqJEpO6NOcdIHzwfdM=/0x0/filters:format(jpeg)/pic361661.jpg",
    summary: "Card-based space empire builder: simultaneous role selection, tableau of worlds and tech.",
    minPlayers: 2,
    maxPlayers: 4,
    minPlaytimeMinutes: 30,
    maxPlaytimeMinutes: 60,
    complexity: 3.0,
    categories: ["Card Game", "Civilization", "Science Fiction"],
    mechanics: ["Hand Management", "Simultaneous Action Selection", "Tableau Building"],
    designers: ["Thomas Lehmann"],
  },
  {
    id: 217124,
    name: "Decrypto",
    yearPublished: 2018,
    thumbnailURL:
      "https://cf.geekdo-images.com/lbxK2lEgs5jZQS9JwhbOiw__thumb/img/X4qjGtdvdvjy8DLBpSO3OvNX7H8=/fit-in/200x150/filters:strip_icc()/pic4540180.png",
    imageURL:
      "https://cf.geekdo-images.com/lbxK2lEgs5jZQS9JwhbOiw__original/img/M_Q9BvGvhX9_M6X_QUUGdlhOLfM=/0x0/filters:format(png)/pic4540180.png",
    summary: "Word-association code-cracking party-deduction; teams crack each other's number sequences.",
    minPlayers: 3,
    maxPlayers: 8,
    minPlaytimeMinutes: 15,
    maxPlaytimeMinutes: 45,
    complexity: 1.9,
    categories: ["Deduction", "Party Game", "Word Game"],
    mechanics: ["Team-Based", "Communication Limits"],
    designers: ["Thomas Dagenais-Lespérance"],
  },
  {
    id: 192291,
    name: "Sushi Go Party!",
    yearPublished: 2016,
    thumbnailURL:
      "https://cf.geekdo-images.com/mz9-V6FHX9bfDxJWSCmnLQ__thumb/img/CW0BJSRFMG5dfQ65MPR8JjQQyVM=/fit-in/200x150/filters:strip_icc()/pic2940434.jpg",
    imageURL:
      "https://cf.geekdo-images.com/mz9-V6FHX9bfDxJWSCmnLQ__original/img/g3VZQAv_Ip8DyzCQHVOtJVgwHJU=/0x0/filters:format(jpeg)/pic2940434.jpg",
    summary: "Cute pass-the-hand sushi drafter; bigger menus and more players than the original.",
    minPlayers: 2,
    maxPlayers: 8,
    minPlaytimeMinutes: 20,
    maxPlaytimeMinutes: 30,
    complexity: 1.5,
    categories: ["Card Game", "Family Game"],
    mechanics: ["Card Drafting", "Set Collection"],
    designers: ["Phil Walker-Harding"],
  },
  {
    id: 256916,
    name: "Cascadia",
    yearPublished: 2021,
    thumbnailURL:
      "https://cf.geekdo-images.com/4Z4_GtqPiP9Z0CzkSpeDrA__thumb/img/CR5ekIjAitU0eYxxqDOEQiLIqLE=/fit-in/200x150/filters:strip_icc()/pic5639817.png",
    imageURL:
      "https://cf.geekdo-images.com/4Z4_GtqPiP9Z0CzkSpeDrA__original/img/aPUyPhnDX2yAHZNxOk_K1bX8Yqw=/0x0/filters:format(png)/pic5639817.png",
    summary: "Drafting habitat tiles and wildlife tokens to build a Pacific Northwest ecosystem.",
    minPlayers: 1,
    maxPlayers: 4,
    minPlaytimeMinutes: 30,
    maxPlaytimeMinutes: 45,
    complexity: 1.8,
    categories: ["Animals", "Environmental"],
    mechanics: ["Tile Placement", "Drafting", "Pattern Building"],
    designers: ["Randy Flynn"],
  },
  {
    id: 246900,
    name: "Eldritch Horror",
    yearPublished: 2013,
    thumbnailURL:
      "https://cf.geekdo-images.com/PW7t0_lUF_Z4dWG2ALEqIw__thumb/img/3UhYNzx3pjV-axANxQHgLbV9hAM=/fit-in/200x150/filters:strip_icc()/pic1731946.jpg",
    imageURL:
      "https://cf.geekdo-images.com/PW7t0_lUF_Z4dWG2ALEqIw__original/img/SsRxsQBJrGdvLWNCwVUM3DwN_w8=/0x0/filters:format(jpeg)/pic1731946.jpg",
    summary: "Cooperative Lovecraftian horror around the world; investigators race to seal Ancient Ones.",
    minPlayers: 1,
    maxPlayers: 8,
    minPlaytimeMinutes: 120,
    maxPlaytimeMinutes: 240,
    complexity: 2.9,
    categories: ["Adventure", "Horror", "Mythology"],
    mechanics: ["Cooperative Game", "Dice Rolling", "Variable Powers"],
    designers: ["Corey Konieczka"],
  },
  {
    id: 271324,
    name: "Tapestry",
    yearPublished: 2019,
    thumbnailURL:
      "https://cf.geekdo-images.com/iCu9aIWlGgL5fM_ZTNz06g__thumb/img/wfH-RskqzJBgUZeCyz2HrFcL7e4=/fit-in/200x150/filters:strip_icc()/pic4583606.jpg",
    imageURL:
      "https://cf.geekdo-images.com/iCu9aIWlGgL5fM_ZTNz06g__original/img/fdoYoblE_NTgHccIRJEoXVdR-Bg=/0x0/filters:format(jpeg)/pic4583606.jpg",
    summary: "Civ from antiquity to space: choose tracks (science, exploration, military, technology) and stack income.",
    minPlayers: 1,
    maxPlayers: 5,
    minPlaytimeMinutes: 90,
    maxPlaytimeMinutes: 120,
    complexity: 2.9,
    categories: ["Civilization", "Economic"],
    mechanics: ["Variable Powers", "Tile Placement", "Income"],
    designers: ["Jamey Stegmaier"],
  },
  {
    id: 312484,
    name: "Lost Ruins of Arnak",
    yearPublished: 2020,
    thumbnailURL:
      "https://cf.geekdo-images.com/6GqH14TJJhqUDH7M-QyNGw__thumb/img/p_giXHvDWoG3UskOKpxfYS6tBSg=/fit-in/200x150/filters:strip_icc()/pic5674958.jpg",
    imageURL:
      "https://cf.geekdo-images.com/6GqH14TJJhqUDH7M-QyNGw__original/img/q73vnPJ3epYmnuW1zUGMFE5VZTQ=/0x0/filters:format(jpeg)/pic5674958.jpg",
    summary: "Deck-builder meets worker-placement: archaeology expedition uncovers idols and monsters.",
    minPlayers: 1,
    maxPlayers: 4,
    minPlaytimeMinutes: 30,
    maxPlaytimeMinutes: 120,
    complexity: 2.9,
    categories: ["Adventure", "Exploration"],
    mechanics: ["Deck Building", "Worker Placement", "Modular Board"],
    designers: ["Elwen", "Mín"],
  },
  {
    id: 254640,
    name: "Root",
    yearPublished: 2018,
    thumbnailURL:
      "https://cf.geekdo-images.com/JUAUWaVmppI23k1tCwQc7w__thumb/img/0WJYqqCq11Q5pdtP0AItRXX73R8=/fit-in/200x150/filters:strip_icc()/pic4254509.jpg",
    imageURL:
      "https://cf.geekdo-images.com/JUAUWaVmppI23k1tCwQc7w__original/img/oVYvYnWZAIbyB-OIN-RWEjSxK6E=/0x0/filters:format(jpeg)/pic4254509.jpg",
    summary: "Asymmetric woodland war: cats, birds, raccoons, and rebels fight for the forest.",
    minPlayers: 2,
    maxPlayers: 4,
    minPlaytimeMinutes: 60,
    maxPlaytimeMinutes: 90,
    complexity: 3.8,
    categories: ["Animals", "Fighting", "Wargame"],
    mechanics: ["Area Control", "Hand Management", "Variable Powers"],
    designers: ["Cole Wehrle"],
  },
  {
    id: 234277,
    name: "The Mind",
    yearPublished: 2018,
    thumbnailURL:
      "https://cf.geekdo-images.com/PT6mb0XPBEJzbsg-Vs-eMQ__thumb/img/lbJDaCH2VrkGKhrJsHCsR67Iaw0=/fit-in/200x150/filters:strip_icc()/pic3979606.png",
    imageURL:
      "https://cf.geekdo-images.com/PT6mb0XPBEJzbsg-Vs-eMQ__original/img/2GpO8oeqzePjE0d6q2Y1Wm-uyko=/0x0/filters:format(png)/pic3979606.png",
    summary: "Cooperative no-talking number-card game: just feel the vibes and play in ascending order.",
    minPlayers: 2,
    maxPlayers: 4,
    minPlaytimeMinutes: 15,
    maxPlaytimeMinutes: 20,
    complexity: 1.1,
    categories: ["Card Game", "Real-time"],
    mechanics: ["Cooperative Game", "Communication Limits"],
    designers: ["Wolfgang Warsch"],
  },
  {
    id: 175914,
    name: "Food Chain Magnate",
    yearPublished: 2015,
    thumbnailURL:
      "https://cf.geekdo-images.com/3oFFA6ZOqjT7r_GDEmnMGw__thumb/img/4MnA0vw3ifH88OMXupVjF1QlZME=/fit-in/200x150/filters:strip_icc()/pic2492582.jpg",
    imageURL:
      "https://cf.geekdo-images.com/3oFFA6ZOqjT7r_GDEmnMGw__original/img/dWeBvJWVmw1JkNpFN_tphz5J05o=/0x0/filters:format(jpeg)/pic2492582.jpg",
    summary: "Ruthless 1950s fast-food empire builder: hire, market, expand, crush competitors.",
    minPlayers: 2,
    maxPlayers: 5,
    minPlaytimeMinutes: 120,
    maxPlaytimeMinutes: 240,
    complexity: 4.2,
    categories: ["Economic", "Industry / Manufacturing"],
    mechanics: ["Variable Powers", "Network and Route Building", "Hand Management"],
    designers: ["Jeroen Doumen", "Joris Wiersinga"],
  },
  {
    id: 84876,
    name: "The Castles of Burgundy",
    yearPublished: 2011,
    thumbnailURL:
      "https://cf.geekdo-images.com/raXuRtYEz6FSWfo5jZsLcQ__thumb/img/W4G6gbFuHdg9I2UFvRwgs-3X-x4=/fit-in/200x150/filters:strip_icc()/pic1176894.jpg",
    imageURL:
      "https://cf.geekdo-images.com/raXuRtYEz6FSWfo5jZsLcQ__original/img/qB5xCkqJrDF2y9aUZN0pxhuD08w=/0x0/filters:format(jpeg)/pic1176894.jpg",
    summary: "Tile-laying dukedom builder; mine, ranch, ship, and trade in dice-driven puzzle goodness.",
    minPlayers: 2,
    maxPlayers: 4,
    minPlaytimeMinutes: 30,
    maxPlaytimeMinutes: 90,
    complexity: 3.0,
    categories: ["Dice", "Medieval", "Territory Building"],
    mechanics: ["Tile Placement", "Dice Rolling", "Set Collection"],
    designers: ["Stefan Feld"],
  },
  {
    id: 251247,
    name: "Barrage",
    yearPublished: 2019,
    thumbnailURL:
      "https://cf.geekdo-images.com/h32oQwQDEpW8B6IQq8oHvw__thumb/img/Wi5T3eJZ3hX1qC8UGEiOnbsv1H4=/fit-in/200x150/filters:strip_icc()/pic4336469.png",
    imageURL:
      "https://cf.geekdo-images.com/h32oQwQDEpW8B6IQq8oHvw__original/img/x6KUYEwgjGzyRyWMy4SpbZ1KrCo=/0x0/filters:format(png)/pic4336469.png",
    summary: "Hydroelectric dam-building economic strategy in alternate-history 1930s Europe.",
    minPlayers: 1,
    maxPlayers: 4,
    minPlaytimeMinutes: 60,
    maxPlaytimeMinutes: 120,
    complexity: 4.1,
    categories: ["Economic", "Industry / Manufacturing"],
    mechanics: ["Worker Placement", "Variable Powers", "Resource Management"],
    designers: ["Tommaso Battista", "Simone Luciani"],
  },
  {
    id: 205637,
    name: "Arboretum",
    yearPublished: 2015,
    thumbnailURL:
      "https://cf.geekdo-images.com/lJxwaktgUcnQYjpXhPWIIw__thumb/img/B4O8jFfczF87M4S40Pt1ZK4ZIyo=/fit-in/200x150/filters:strip_icc()/pic3023205.jpg",
    imageURL:
      "https://cf.geekdo-images.com/lJxwaktgUcnQYjpXhPWIIw__original/img/0iUv-_VOI_PRSskuIv_8FW3SwXM=/0x0/filters:format(jpeg)/pic3023205.jpg",
    summary: "Plant the prettiest tree-lined paths in the village arboretum; brutal endgame scoring.",
    minPlayers: 2,
    maxPlayers: 4,
    minPlaytimeMinutes: 25,
    maxPlaytimeMinutes: 35,
    complexity: 2.4,
    categories: ["Card Game", "Environmental"],
    mechanics: ["Hand Management", "Set Collection"],
    designers: ["Dan Cassar"],
  },
  {
    id: 269207,
    name: "Maracaibo",
    yearPublished: 2019,
    thumbnailURL:
      "https://cf.geekdo-images.com/pcsxKFMz72YzPAUoF9fBgg__thumb/img/Yt9cfaCiD1G_lXr8Y45HD1c2L9Q=/fit-in/200x150/filters:strip_icc()/pic4729746.jpg",
    imageURL:
      "https://cf.geekdo-images.com/pcsxKFMz72YzPAUoF9fBgg__original/img/iyV0SPKpYL2lYFRm8jkF8WFiFKE=/0x0/filters:format(jpeg)/pic4729746.jpg",
    summary: "17th-century Caribbean: sail a circular route, pick a faction, narrate a multi-game story.",
    minPlayers: 1,
    maxPlayers: 4,
    minPlaytimeMinutes: 30,
    maxPlaytimeMinutes: 120,
    complexity: 3.7,
    categories: ["Adventure", "Economic", "Nautical"],
    mechanics: ["Variable Powers", "Card Drafting", "Network and Route Building"],
    designers: ["Alexander Pfister"],
  },
  {
    id: 220877,
    name: "Clans of Caledonia",
    yearPublished: 2017,
    thumbnailURL:
      "https://cf.geekdo-images.com/oRLcZeWyQXR_3IAQbCBsIA__thumb/img/SeNAHEyrGtS9pGYsh-AdaFQQU0Y=/fit-in/200x150/filters:strip_icc()/pic3586414.jpg",
    imageURL:
      "https://cf.geekdo-images.com/oRLcZeWyQXR_3IAQbCBsIA__original/img/8u8C7HLjLMTnUTw18vBxZJ_eVic=/0x0/filters:format(jpeg)/pic3586414.jpg",
    summary: "19th-century Scottish clans trade whisky, herd sheep, and export to England.",
    minPlayers: 1,
    maxPlayers: 4,
    minPlaytimeMinutes: 30,
    maxPlaytimeMinutes: 120,
    complexity: 3.4,
    categories: ["Economic", "Farming"],
    mechanics: ["Network and Route Building", "Variable Powers", "Tile Placement"],
    designers: ["Juma Al-JouJou"],
  },
  {
    id: 263918,
    name: "Calico",
    yearPublished: 2020,
    thumbnailURL:
      "https://cf.geekdo-images.com/jPUgaPBdcKAcyLzPkRu7FA__thumb/img/aETt8dUzJX4t2c3WXdIEjtBOuvE=/fit-in/200x150/filters:strip_icc()/pic5234822.png",
    imageURL:
      "https://cf.geekdo-images.com/jPUgaPBdcKAcyLzPkRu7FA__original/img/uH3WMUtAZBsJuqVV8C0pPtPZF1c=/0x0/filters:format(jpeg)/pic5234822.png",
    summary: "Stitch a cat-friendly quilt: hexagonal tile drafting and pattern matching.",
    minPlayers: 1,
    maxPlayers: 4,
    minPlaytimeMinutes: 30,
    maxPlaytimeMinutes: 60,
    complexity: 2.6,
    categories: ["Animals", "Abstract Strategy"],
    mechanics: ["Pattern Building", "Tile Placement"],
    designers: ["Kevin Russ"],
  },
  {
    id: 295486,
    name: "It's a Wonderful World",
    yearPublished: 2019,
    thumbnailURL:
      "https://cf.geekdo-images.com/lq8jKFQX5lTd-d0FFJC3rA__thumb/img/29ELpchQwR4UoZAg9V_QPLO7QXk=/fit-in/200x150/filters:strip_icc()/pic4828589.jpg",
    imageURL:
      "https://cf.geekdo-images.com/lq8jKFQX5lTd-d0FFJC3rA__original/img/6YyB1pFBrMWb2W2BICdSWsQDQ4Q=/0x0/filters:format(jpeg)/pic4828589.jpg",
    summary: "Card-drafting empire engine: blueprint cards become production each turn.",
    minPlayers: 1,
    maxPlayers: 5,
    minPlaytimeMinutes: 30,
    maxPlaytimeMinutes: 45,
    complexity: 2.4,
    categories: ["Card Game", "Civilization", "Economic"],
    mechanics: ["Card Drafting", "Simultaneous Action Selection", "Engine Building"],
    designers: ["Frédéric Guérard"],
  },
  {
    id: 285774,
    name: "Marvel Champions: The Card Game",
    yearPublished: 2019,
    thumbnailURL:
      "https://cf.geekdo-images.com/UxPjiNuIdgr8fyrR0gd3Ig__thumb/img/9p5xzTkHbnuJ7gmTeaCjGmdRTHQ=/fit-in/200x150/filters:strip_icc()/pic4922881.png",
    imageURL:
      "https://cf.geekdo-images.com/UxPjiNuIdgr8fyrR0gd3Ig__original/img/RfygqM4HUkuwdzlmoCMvRfxBXJk=/0x0/filters:format(jpeg)/pic4922881.png",
    summary: "Cooperative Living Card Game: heroes team up against scenarios from the Marvel universe.",
    minPlayers: 1,
    maxPlayers: 4,
    minPlaytimeMinutes: 45,
    maxPlaytimeMinutes: 90,
    complexity: 2.6,
    categories: ["Card Game", "Comic Book / Strip", "Fighting"],
    mechanics: ["Cooperative Game", "Hand Management", "Variable Powers"],
    designers: ["Michael Boggs", "Nate French", "Caleb Grace"],
  },
  {
    id: 260605,
    name: "Brass: Birmingham (Deluxe)",
    yearPublished: 2018,
    thumbnailURL:
      "https://cf.geekdo-images.com/x3zxjr-Vw5iU4yDPg70Jgw__thumb/img/u8DBLG6BPcpdRP_LIs7-_3l9pyc=/fit-in/200x150/filters:strip_icc()/pic3490053.jpg",
    imageURL:
      "https://cf.geekdo-images.com/x3zxjr-Vw5iU4yDPg70Jgw__original/img/FpyxlSVOLEsdXcTOPGXpgBaJYjU=/0x0/filters:format(jpeg)/pic3490053.jpg",
    summary: "Deluxe edition of Brass: Birmingham — same gameplay, premium components.",
    minPlayers: 2,
    maxPlayers: 4,
    minPlaytimeMinutes: 60,
    maxPlaytimeMinutes: 120,
    complexity: 3.9,
    categories: ["Economic", "Industry / Manufacturing"],
    mechanics: ["Hand Management", "Network and Route Building", "Loans"],
    designers: ["Martin Wallace"],
  },
] as const;
